// Code generated by protoc-gen-gogo.
// source: snapshot.proto
// DO NOT EDIT!

/*
Package snapshot is a generated protocol buffer package.

It is generated from these files:
	snapshot.proto

It has these top-level messages:
	Snapshot
*/
package snapshot

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Snapshot struct {
	Buffers          []*SnapshotBuffer `protobuf:"bytes,1,rep,name=buffers" json:"buffers,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}

func (m *Snapshot) GetBuffers() []*SnapshotBuffer {
	if m != nil {
		return m.Buffers
	}
	return nil
}

type SnapshotBuffer struct {
	Key              *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Messages         [][]byte `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SnapshotBuffer) Reset()         { *m = SnapshotBuffer{} }
func (m *SnapshotBuffer) String() string { return proto.CompactTextString(m) }
func (*SnapshotBuffer) ProtoMessage()    {}

func (m *SnapshotBuffer) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SnapshotBuffer) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
}
